<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Storing request</title>
</head>
<body>
	<%
		String city = request.getParameter("summCityName");
		if (city == null || city.length() == 0) {
			%>
			<script>
				alert("Please input destination city name");
				window.location.href = "revenueReports.jsp";
			</script>
			<%
			return;
		}

		try {
			//Create a connection string

			String url = "jdbc:mysql://cs539-fzj-spring18.cqcdjb7jk2qs.us-east-2.rds.amazonaws.com:3306/hwproject";
			Class.forName("com.mysql.jdbc.Driver");

			//Create a connection to your DB
			Connection con = DriverManager.getConnection(url, "fzj", "Ru151718~");
			
			// 1. check whether the airport_id exists
			String strQuery = " SELECT airport_id  FROM AIRPORT WHERE  city=?;";
			PreparedStatement stm = con.prepareStatement(strQuery);
			stm.setString(1, city);
			//System.out.println(" debuggable statement= " + stm.toString());
			ResultSet rs = stm.executeQuery();
			//if(!rs.isBeforeFirst()){
			if(!rs.next()){
				%>
				<script>
					alert("Sorry, the city does not exist");
					window.location.href = "revenueReports.jsp";
				</script>
				<%
				con.close();
				return;
			} 
						
			String airportId = rs.getString("airport_id");

			strQuery = "SELECT F.to_air,  L.airline_id,L.flight_num,SUM(R.total_fee) total_revenue "
					+ " FROM FLIGHT F, LEG L, RESERVATION R "
					+ " WHERE F.to_air = ? AND F.airline_id =  L.airline_id AND F.flight_num = L.flight_num AND L.reserve_num = R.reserve_num"
					+ " GROUP BY  F.airline_id, F.flight_num;";

			stm = con.prepareStatement(strQuery);
			stm.setString(1, airportId);

 			//System.out.println(" debuggable statement= " + stm.toString());
			rs = stm.executeQuery();
			if(!rs.isBeforeFirst()){
				%>
				<script>
					alert("Sorry, no data to summary for this city.");
					window.location.href = "revenueReports.jsp";
				</script>
				<%
				con.close();
				return;
			}
			
			ResultSetMetaData md = rs.getMetaData();

			List<String> columns = new ArrayList<String>();
			int rowCount = md.getColumnCount();
			for (int i = 1; i <= rowCount; i++) {
				columns.add(md.getColumnName(i));
			}
			
			//Data structure to hold result set
			List<String[]> results = new ArrayList<String[]>();
			while (rs.next()) {
				String[] row = new String[rowCount];
				for (int i = 1; i <= rowCount; i++) {
					row[i - 1] = rs.getString(columns.get(i - 1));
				}
				results.add(row);
			}

			String queryType = "Revenue Generated by Destination City '" + city + "': ";
			request.setAttribute("columns", columns);
			request.setAttribute("results", results);
			request.setAttribute("querytype", queryType);

			con.close();

			RequestDispatcher rd = request.getRequestDispatcher("mgrQueryResults.jsp");
			rd.forward(request, response);

		} catch (Exception e) {
			out.println(e);
			e.printStackTrace();
		}

		response.setContentType("text/html");
	%>

</body>
</html>