<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link rel="stylesheet" href="/resources/demos/style.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>

	<%
		String mgAccount = session.getAttribute("account").toString();
		out.print( "<p class='message' > Welcome! Dear " + mgAccount + "</p>");
	%>
<h2>Revenue Reports</h2>
<div id="accordion">
  <h3>Revenue Summary</h3>
  <div>
    <p>
      Produce a summary listing of revenue generated by a particular flight, 
      destination city, or customer
    </p>
    <form name="summbyflight" action="revenueSummaryByFlight.jsp" method="post">
      Flight Number: <input class="textbox" type="text" value="CA819" name="summFlightNumber">
      <button type="submit">Query</button>
    </form>
    <br>or<br>
    <form name="summbycity" action="revenueSummaryByCity.jsp" method="post">
<!--      Destination City: <input class="textbox" type="text" value= "BEIJING" name="summCityName"> -->
     Destination City: <input class="textbox" type="text" value= "SEATTLE" name="summCityName">
      <button type="submit">Query</button>
    </form>
    <br>or<br>
    <form name="summbycust" action="revenueSummaryByCustomer.jsp" method="post">
    Customer's First Name: <input class="textbox" type="text" value="JINGYI" name="firstName"/><br>
    Customer's Last Name: <input class="textbox" type="text" value="GU" name="lastName"/>  <br>
      <button type="submit">Query</button>
    </form>
  </div>
  
  <h3>Top Customer</h3>
  <div class="content">
    <p>
      Determine which customer generated most total revenue
    </p>
    <form name="cotm" action="revenueTopCustomer.jsp" method="post">
      <button type="submit">Query</button>
    </form>
  </div>
</div>
<p class='message'> <br><br>Go Back? <a href='managerHomePage.jsp'> Go Back</a></p>
</body>
 <script>
    $(function() {
      $("#accordion").accordion({
        active: parseInt(getAnchor(location.href)),
        heightStyle: "content"
      });
    });
    
    function getAnchor(url)
    {
      var index = url.lastIndexOf('#');
      if (index != -1)
        return url.substring(index+1);
    }
  
</script>
</html>
